version: '3'
services:
   workshop:
      image: springboot:v11 
      build:
         context: .
         dockerfile: Dockerfile
      restart: unless-stopped
      #stdin_open: true
      #tty: true
      #command: sh
      #environment:
      # - DEBUG=true
      ports:
        - 80:8080
      #   - ${API_PORT}:${API_PORT}
networks:
   default:
      external: true
      name: workshop     
